#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

if [ -z $ZSH_ENV_LOADED ]; then
  set cargo path
  export PATH="$HOME/.cargo/bin:$PATH"

  # set XDG_CONFIG_HOME
  export XDG_CONFIG_HOME=~/.config

  # go path
  if [ -d ${GOENV_ROOT} ] ; then
    export PATH="$PATH:$GOROOT/bin"
    export PATH="$PATH:$GOPATH/bin"
  fi

  if [ -d ${HOME}/.pub-cache ] ; then
    export PUB_CACHE_PATH="$HOME/.pub-cache"
    export PATH="$PATH":"$PUB_CACHE_PATH/bin"
  fi

  if [ -d ${HOME}/flutter ] ; then
    export FLUTTER_PATH="$HOME/flutter"
    export PATH="$PATH":"$FLUTTER_PATH/bin"
  fi

  if [ -d ${HOME}/.poetry ] ; then
    export POETRY_PATH="$HOME/.poetry"
    export PATH="$PATH":"$POETRY_PATH/bin"
  fi

  # To enable auto-actimation, pyenv-virtualenv
  if which pyenv-virtualenv-init > /dev/null; then
    eval "$(pyenv virtualenv-init -)";
  fi

  # for binutils
  if [ -d /usr/local/opt/binutils ]; then
    export PATH="/usr/local/opt/binutils/bin:$PATH"
    export LDFLAGS="-L/usr/local/opt/binutils/lib"
    export CPPFLAGS="-I/usr/local/opt/binutils/include"
  fi

  # for imagemagick
  if [ -e /usr/local/bin/convert ]; then
    export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"
  fi

  export ZSH_ENV_LOADED="1"
else

  # To enable auto-actimation, pyenv-virtualenv
  if which pyenv-virtualenv-init > /dev/null; then
    eval "$(pyenv virtualenv-init -)";
  fi
    print "already loaded .zshenv"
fi
