#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# set pyenv 
# PYENV_ROOT=~/.pyenv
# export PATH=$PATH:$PYENV_ROOT/bin
# eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"

# open blender by terminal
alias blender=/Applications/Blender/blender.app/Contents/MacOS/blender

# set nodebrew
NODEBREW_ROOT=$HOME/.nodebrew
export PATH=$PATH:$NODEBREW_ROOT/current/bin

# set Python Library Path
PYLIB3_ROOT=$HOME/Library/Python/3.7
export PATH=$PATH:$PYLIB3_ROOT/bin

# set cargo path
export PATH="$HOME/.cargo/bin:$PATH"

# set XDG_CONFIG_HOME
export XDG_CONFIG_HOME=~/.config
