#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# # Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# lsのエイリアス
alias la='ls -A'
alias lg='ls -Agh'
alias ll='ls -Ahl'
# 隠しファイルのみ表示
alias ld='ls -dh .*'
alias lld='ls -ldh .*'

# 確認
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# 省略
alias v=nvim
alias e=echo
alias th=touch

# sudo の後のコマンドでエイリアスを有効にするらしい
alias sudo='sudo '

# クリップボードにコピー
alias pb='pbcopy <'
alias -g C='| pbcopy' #個人的にこれがクソ便利です

# 出力からgrep
alias -g G='| grep'

# 設定ファイルをどっからでもすぐ開く
alias -g zrc='~/.zshrc'

# git関連お好みで
alias g=git
alias gad='git add'
alias gau='git add -u'
alias gaa='git add -A'
alias gc='git commit -m'
alias gl='git log --oneline'
alias gs='git status -sb'

#ctags override
# alias ctags='/usr/local/bin/ctags'
alias ctags="`brew --prefix`/bin/ctags"

# 設定即反映
alias sz='source ~/.zshrc' #これもクソ便利です

# Preztoアップデート
alias preup='cd ~/.zprezto && git pull && git submodule update --init --recursive ; cd -'

# $PATHに登録されているpathの操作
path_append () { path_remove $1; export PATH="$PATH:$1"; }
path_prepend () { path_remove $1; export PATH="$1:$PATH"; }
path_remove () { export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }

# $fpath 追加
if [ -e /usr/local/share/zsh-completions ]; then
  fpath=(/usr/local/share/zsh-completions/src $fpath)
fi

# 追加補完を有効
autoload -Uz compinit
compinit

# source fzf config
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# source z.sh
[ -f ~/.ghq/github.com/rupa/z/z.sh ] && source ~/.ghq/github.com/rupa/z/z.sh

# fzf-z-search() keybind
zle -N fzf-z-search
bindkey '^f' fzf-z-search
